# Generated by Django 4.1.3 on 2022-11-23 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingAuthor', models.SmallIntegerField(default=0)),
                ('name', models.CharField(max_length=120)),
                ('authorUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_text', models.CharField(max_length=255)),
                ('pub_datetime', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('pub_datetime', models.DateTimeField(auto_now_add=True)),
                ('article_text', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('categoryType', models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], default='AR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_name',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='postcategory',
            name='cat_rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practic.category'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='post_rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practic.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='cat_rel',
            field=models.ManyToManyField(through='practic.PostCategory', to='practic.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practic.author'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_rela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practic.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_relat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
